### PR TITLE
Fix concurrent writes to compiled files

### LINKED ISSUE #185: Random errors during typescript compilation
Hello guys!

I was using ts-node-dev@1.0.0-pre.54 with node v12.13.0 and random errors appeared at compilation time.

Examples: 
 - XY is not a contstructor. (XY is never the same)
 - Can not read property of undefined (e.g. enums, functions, etc. )

I've been looking for a solution, I found out that @1.0.0-pre.44 work perfectly, but other versions failed to compile the project. When using @1.0.0-pre.54 version, pressing Ctrl+S on the root file (index.ts), it starts to recompile then  fails maximum 1 or 2 times and works after that. If I restart with npm start then it fails always at first.

My start script: 
"start": "set debug=* && tsnd --respawn --ignore-watch node_modules --debug --transpile-only src/index.ts"

I am using Windows 10 with WSL enabled. 

Moreover, this is not a "random behaviour" 4 computers (windows 10) reproduce it, but on linux works fine. 

Any idea what's going on?

Thanks in advance.

PS.: If you need any info, just let me know.

### PR DESCRIPTION
**Pull request by Sytten**
Should fix #185 and #209 
Check the comment https://github.com/whitecolor/ts-node-dev/issues/185#issuecomment-726375197 and following for the full investigation.
The choice of `proper-lockfile` is personal, `lockfile` could most likely do the job too.

### CODE REVIEW

**Comment by Sytten** [comment]
BTW tests are failing on master on my end so I can't test if I broke something. @whitecolor do they work on your machine?

**Comment by whitecolor** [comment]
@Sytten yes they work on my machine, not sure why it doesn't work on travis. What error do you get running tests?

**Comment by whitecolor** [comment]
> Should fix #185 and #209

I've read you post in the issue.

> No sure why it sometimes compile the file twice and I hope it won't fuck up reload if two compilation message are processed back to back. Anyway a PR will be out shortly.

Can you explain what is actually happening, isn't there a way to reproduce the case?

**Comment by Sytten** [comment]
Ok good to know, here all the tests timeout since they take more than 5000ms. Not sure why.

For the comment, once I removed the duplicate call to `writeCompiled` it removed 90% of the problems but I still saw some concurrent writes. That is why I added the write lock. But the root cause is really that something calls the `compiler.compile(...)` for the same file twice, but I could not find why that was the case. 

What I also meant is that each time you save a file, it emits a signal by the watcher so if you save twice really fast the file, there is a chance that the first write will succeed in writing a compiled version an older version file version and that the second write is ignored but I think this is relatively improbable. I didn't dig into it to verify.

**Comment by whitecolor** [comment]
> Ok good to know, here all the tests timeout since they take more than 5000ms. Not sure why.

You may try to run `yarn test-dev` see if there is some output. And probalby quite easy to debug what is going on in tests (look at  `test/spawn.ts` for example).

> there is a chance that the first write will succeed in writing a compiled version an older version file version and that the second write 

Ok I see, maybe there there is really some issue with chokidar change events handling. Do you use `--poll` option? I usually use it as run mostly in docker. And not sure why sync write cause the issue.

**Comment by Sytten** [comment]
I will try, maybe it would be nice too setup some github actions too.

I dont use any option since it runs on my machine most of the time. I think its going to be OK honestly.
As to sync write, this is a typical problem for all OS you should always protect the writes with a lock.
Do you nee anything more from me before merging?

**Comment by Sytten** [comment]
@whitecolor Just making sure you saw my previous comment

**Comment by whitecolor** [comment]
@Sytten Yes I've seen, I want to look at it more carefully, yet not sure if using additional locking is the right way to solve the issue.

**Comment by Sytten** [comment]
Fair. I would like to point out that it did not seem to affect performances and it's pretty much a requirement for any code where multiple concurrent things could write to the same file. Think of it as a mutex on a shared memory pool.

**Comment by Sytten** [comment]
Until the problem is fixed, I publish my fixed version https://www.npmjs.com/package/@sytten/ts-node-dev
I will keep it updated with upstream it is properly fixed here.

**Comment by vimutti77** [comment]
It works for me.

**Comment by flandrade** [comment]
ts-node-dev hangs for me since v1.0.0-pre.45. This fixed the problem. Thanks, @Sytten!

**Comment by whitecolor** [comment]
@Sytten if not to use sync writes? We are not limited to do it here.

To to replace sync writes with:
```
fs.writeFile(compiledPath, code, (err) => {
          err && log.error(err)
          fs.writeFile(compiledPath + '.done', '', (err) => {
            err && log.error(err)
          })
        })
```

**Comment by Sytten** [comment]
In theory that could work since node is single threaded. But it was already a sync write unless I am mistaken so that suggests the callback was executed by different processes?
I also found that the current solution is not perfect, if you save twice a watched file I saw some pipes errors happening.

**Comment by whitecolor** [comment]
> In theory that could work since the node is single-threaded.

So please try it for your cases, and report back, because I can not reproduce the error to check.

>  if you save twice a watched file I saw some pipes errors happening.

I guess something would be done in watching logic. An output log or screenshot would be helpful.

**Comment by Sytten** [comment]
Honestly I am surprised you can't reproduce it was a really common issue for me and i was having trouble multiple times a day on MacOS. And I was not the only one by the comments I received on the linked issue and this PR. If the promisified  version of fs doesn't work I don't see how the callback version could work either, the problem is concurrent writes which are triggered by concurrent compilation requests (which in itself is a problem that this PR doesnt fix). Did you try on a project with more than couple hundred files? I found it occurs more often the bigger the project.

**Comment by whitecolor** [comment]
> Honestly I am surprised you can't reproduce it was a really common issue for me and i was having trouble multiple times a day on MacOS. And I was not the only one by the comments I received on the linked issue and this PR. If the promisified version of fs doesn't work I don't see how the callback version could work either, the problem is concurrent writes which are triggered by concurrent compilation requests (which in itself is a problem that this PR doesnt fix). Did you try on a project with more than a couple hundred files? I found it occurs more often the bigger the project.

I use it with docker containers (with dev volumes attached from host) and with `--poll` option enabled. Also, (micro-)services I use it with not very big.

> the problem is concurrent writes which are triggered by concurrent compilation requests

A concurrent write occurs to different files. I don't really get how the file ock helps here. Can you explain the mechanics, what do we prevent here with the file lock?

**Comment by Sytten** [comment]
> I use it with docker containers (with dev volumes attached from host) and with `--poll` option enabled. Probably this is the main reason I've seen no fs related issues. Also, (micro-)services I use it with are not very big.
That could make sense yeah.

> Concurrent writes occur to different files. I don't really get how the file ock helps here. Can you explain the mechanics, what do we prevent here with the file lock?

That's the thing, I see occasional concurrent writes for the same file. This caused the weird errors that I wrote about in my investigation. The origin of those problematic concurrent files could maybe be due to a lack of debouncing on change (I have seen it happen)? But even then it would not explain why a first compilation sometimes fail. I didn't dig deep into how it finds the files it needs to compile so there might be an issue there too.
My point is that despite all that, the fact that a concurrent write can happen is a case for using a lock. Mind you that this is not a lock for all files, but a lock on each file name so you still can do concurrent writes to different files.

**Comment by Sytten** [comment]
@whitecolor Here is the issue I sometimes get:
```
Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:676:19)
    at Object.exports.send (/Users/Sytten/Projects/REDACTED/api/node_modules/@sytten/ts-node-dev/lib/ipc.js:17:14)
    at /Users/Sytten/Projects/REDACTED/api/node_modules/@sytten/ts-node-dev/lib/wrap.js:88:9
    at Object.nodeDevHook [as .ts] (/Users/Sytten/Projects/REDACTED/api/node_modules/@sytten/ts-node-dev/lib/hook.js:61:17)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Sytten/Projects/REDACTED/api/src/utils/index.ts:6:1)
```
Unrelated to the issue at hand, but also annoying. Most likely due to a lack of debouncing.

**Comment by whitecolor** [comment]
> That's the thing, I see occasional concurrent writes for the same file. 

This definitely should be the case. So need to figure out why and prevent this. Actually, the path is unique because it is composed of content hash, so it should be easy just to prevent occasional compilation duplication.

**Comment by whitecolor** [comment]
I've published an updated version with the probable fix, please try.

**Comment by Sytten** [comment]
You also need to remove this line https://github.com/whitecolor/ts-node-dev/pull/230/files#diff-041bb58b49fbc5e7fdf9b8d09f0f0ae8d524d727947bcfa3e3d1c91b8a35aeeeL251
@whitecolor Because ts-node already call the callback, so you are calling it twice. This was one of the major source of concurrent writes. But in reality I still don't get the aversion of locks. It does basically the same thing as your fix but there is no chance that it fails and cause weird errors.

**Comment by whitecolor** [comment]
> You also need to remove this line

Thanks for pointing this out. -)

> the aversion of locks.

No aversion, just if additional fs ops can be avoided, should it not be?

**Comment by flipace** [comment]
@whitecolor @Sytten thanks a lot to both of you for tackling this issue - we just updated to `1.1.1` and it works fine again!

**Comment by Sytten** [comment]
Agreed, I will do more testing with the latest changes to see if it fixed the issue on large codebases with contention.
Thanks for the fix @whitecolor

**Pull request closed without merging**
