### PR TITLE
Remove dateformat dependency

### PR DESCRIPTION
**Pull request by daniel-pedersen**
Implementation of https://github.com/wclr/ts-node-dev/pull/273#issuecomment-858491800
Also solves #271

### CODE REVIEW

**Comment by leleofg** [comment]
Any updates?

**Comment by faizjamil** [comment]
@wclr please check this and merge if it works
Would very much not like to have a vuln in my project

**Comment by pexxi** [comment]
This would be highly appreciated!

**Comment by ValeriaVG** [comment]
I am also waiting for this to be merged and published.
By the way, the repository has one more package-lock that needs to be regenerated: [pnpm-lock.yaml](https://github.com/wclr/ts-node-dev/blob/master/pnpm-lock.yaml)

**Comment by anthonyalayo** [comment]
It seems like @wclr is away these days, is it possible to add more maintainers somehow?

**Comment by rshep1** [comment]
> It seems like @wclr is away these days, is it possible to add more maintainers somehow?

You could fork the repo. I'm afraid that's what I'm going to have to do since this project seems dead.

**Comment by faizjamil** [comment]
Thank you sir

**Comment by anthonyalayo** [comment]
Anyone here mind helping me out as well? Been trying to merge a fix for a month with no luck:
https://github.com/wclr/ts-node-dev/pull/269

If you can kindly bump it -- much appreciated!

**Pull request merged**
